workflows:
    ios-workflow:
      name: iOS Workflow
      integrations:
        app_store_connect: 'unity game' # < -- Put API Key Name from Teams > Settings > Integrations > App Store Connect
      environment:
        ios_signing:
          provisioning_profiles:
            - profile
          certificates:
            - certificate
        #   distribution_type: ad_hoc
        #   bundle_identifier: com.mkas.colorrush
        vars:
          XCODE_WORKSPACE: "Unity-iPhone.xcodeproj" # <-- Put the name of your workspace here.
          XCODE_SCHEME: "Unity-iPhone" # <-- Put the name of your scheme here.
          #APP_STORE_APPLE_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
        branch_patterns:
          - pattern: 'develop'
            include: true
            source: true
      scripts:
        - name: Install CocoaPods dependencies
          script: |
            pod install
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        # - name: Increment build number
        #   script: |
        #     # agvtool new-version -all $(($BUILD_NUMBER + 1))
        #     agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
        # - name: build
        #   script: |
        #     xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -showBuildSettings
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --project "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
