name: Build iOS IPA with Auto Signing

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Archive iOS app
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        gem install cocoapods
        pod install --repo-update

    - name: Set up Apple Developer credentials
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PWD: ${{ secrets.APPLE_PWD }}
      run: |
        echo "FASTLANE_USER=${APPLE_ID}" >> $GITHUB_ENV
        echo "FASTLANE_PASSWORD=${APPLE_PWD}" >> $GITHUB_ENV

    - name: Build and Sign IPA
      run: |
        xcodebuild archive -workspace YourApp.xcworkspace -scheme YourAppScheme -archivePath $PWD/build/YourApp.xcarchive -allowProvisioningUpdates
        xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportPath $PWD/build/ -exportOptionsPlist ExportOptions.plist -allowProvisioningUpdates

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: YourApp.ipa
        path: ${{ github.workspace }}/build/YourApp.ipa
